version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: wallet_backend
      POSTGRES_PASSWORD: C54070a0D01
      POSTGRES_DB: wallet_backend_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://wallet_backend:C54070a0D01@db:5432/wallet_backend_development
    depends_on:
      - db
    volumes:
      - ./backend:/rails
    command: >
      sh -c "bin/rails db:migrate && rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    command: yarn dev --host 0.0.0.0
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    working_dir: /frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  pgdata:

  node_modules:
